package controllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXButton;

import application.Main;
import javafx.scene.Parent;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Pane;

public class SettingFormController implements Initializable{
	@FXML
	private JFXButton settingButton;
	@FXML
	private JFXButton userButton;
	@FXML
	private JFXButton homeButton;
	@FXML
	private JFXButton barchartButton;
	@FXML
	private Pane pane;

	// Event Listener on JFXButton[#settingButton].onMouseClicked
	@FXML
	public void open_setting(MouseEvent event) throws IOException {
		Parent fxml= FXMLLoader.load(getClass().getResource("/views/SettingView.fxml"));
		pane.getChildren().removeAll();
		Main.makeTransition(fxml, pane);
		pane.getChildren().setAll(fxml);
	}
	// Event Listener on JFXButton[#userButton].onMouseClicked
	@FXML
	public void open_user(MouseEvent event) throws IOException {
		Parent fxml= FXMLLoader.load(getClass().getResource("/views/UserView.fxml"));
		pane.getChildren().removeAll();
		Main.makeTransition(fxml, pane);
		pane.getChildren().setAll(fxml);
	}
	// Event Listener on JFXButton[#homeButton].onMouseClicked
	@FXML
	public void open_home(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent fxml= FXMLLoader.load(getClass().getResource("/views/NewUserView.fxml"));
		pane.getChildren().removeAll();
		Main.makeTransition(fxml, pane);
		pane.getChildren().setAll(fxml);
	}
	// Event Listener on JFXButton[#barchartButton].onMouseClicked
	@FXML
	public void open_bar_chart(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent fxml= FXMLLoader.load(getClass().getResource("/views/ListUserView.fxml"));
		pane.getChildren().removeAll();
		Main.makeTransition(fxml, pane);
		pane.getChildren().setAll(fxml);
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		Parent fxml;
		try {
			fxml = FXMLLoader.load(getClass().getResource("/views/SettingView.fxml"));
			pane.getChildren().removeAll();
			Main.makeTransition(fxml, pane);
			pane.getChildren().setAll(fxml);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
